"""Adicionar campos bairro, rua e cep a tabela users

Revision ID: 838ab41dbbbf
Revises: 6c048107cf4f
Create Date: 2025-02-06 10:14:58.919886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838ab41dbbbf'
down_revision = '6c048107cf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bairro', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('rua', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('cep', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cep')
    op.drop_column('users', 'rua')
    op.drop_column('users', 'bairro')
    # ### end Alembic commands ###
